#ifndef CME_ORDER_BOOK_ORDER_BOOK_HPP
#define CME_ORDER_BOOK_ORDER_BOOK_HPP

#include <cstddef>
#include <map>
#include <optional>

#include "cme/order/order.hpp"
#include "cme/order_book/price_level.hpp"
#include "cme/order/order_validation.hpp"
#include "cme/trade/trade.hpp"

/* Stores the buy and sell price levels for one trading symbol. */
class CMEOrderBook
{
public:
    /* Creates an empty order book for one trading symbol. */
    explicit CMEOrderBook(CMESymbol symbol);

    /* Returns the trading symbol represented by this order book. */
    CMESymbol getSymbol() const;

    /* Validates and adds a limit order to the correct side of the order book. */
    bool addLimitOrder(CMEOrder incomingOrder);

    /* Returns the number of buy price levels currently stored. */
    std::size_t getBuyLevelCount() const;

    /* Returns the number of sell price levels currently stored. */
    std::size_t getSellLevelCount() const;

    /* Returns the buy price level stored at a specific price. */
    const CMEPriceLevel& getBuyLevel(CMEPrice price) const;

    /* Returns the sell price level stored at a specific price. */
    const CMEPriceLevel& getSellLevel(CMEPrice price) const;

    /* Returns the highest buy price currently stored. */
    CMEPrice getBestBid() const;

    /* Returns the lowest sell price currently stored. */
    CMEPrice getBestAsk() const;

    /* Returns the most recently generated trade. */
    const std::optional<CMETrade>& getLastTrade() const;

    /* Creates a trade describing one completed match. */
    void createTrade(const CMEOrder& incomingOrder, const CMEOrder& restingOrder, CMEQuantity tradeQuantity);

    /* Removes an order from the order book using its order identifier. */
    bool cancelOrder(CMEOrderId orderId);

    /* Replaces an existing order using a new price and quantity. */
    bool modifyOrder(CMEOrderId orderId, CMEPrice newPrice, CMEQuantity newQuantity);

private:
    // The trading symbol represented by this order book.
    CMESymbol bookSymbol; 

    // The buy price levels indexed by their numeric price.
    std::map<std::int64_t, CMEPriceLevel> buyLevels; 

    // The sell price levels indexed by their numeric price.
    std::map<std::int64_t, CMEPriceLevel> sellLevels;

    // The validator used to check orders before they enter the order book.
    CMEOrderValidator orderValidator;

    // The most recent trade generated by this order book.
    std::optional<CMETrade> lastTrade;

    // The identifier assigned to the next generated trade
    std::uint64_t nextTradeId;

    /* Returns whether any buy price levels exist. */
    bool hasBuyLevels() const;

    /* Returns whether any sell price levels exist. */
    bool hasSellLevels() const;

    /* Returns whether an incoming order crosses the best opposite price. */
    bool canMatch(const CMEOrder &incomingOrder) const;

    /* Attempts to match an incoming order against the best opposite order. */
    bool tryMatchOrder(CMEOrder &incomingOrder);

    /* Removes an empty price level from the selected side of the order book. */
    void removeEmptyLevel(CMESide side, CMEPrice price);

    /* Finds and copies the order with the supplied identifier. */
    bool findOrder(CMEOrderId orderId, CMEOrder& foundOrder) const;
};
#endif // CME_ORDER_BOOK_ORDER_BOOK_HPP